spring:
  application:
    name: mybatis-generater
  datasource:
    password: Sandu_218root
    username: root
    url: jdbc:mysql://192.168.1.107:3306/app_online_30?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driverClassName: com.mysql.jdbc.Driver
    type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource


debug: true

server:
  port: 10010
